spring:
  datasource:
    url: jdbc:h2:mem:kpay
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

#  h2:
#    console:
#      enabled: false
#      console.path: /testdb

  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hiberante.ddl-auto: update
    properties.hibernate.default_batch_fetch_size: 100

hibernate:
  show_sql: true
